### ISSUE TITLE
Android TV

### ISSUE THREAD

**Issue by magico1010** [Fluffistar/NEtFLi-Android#1]
Hi
Danke für deine APP.
Wäre es möglich das deine APP auf Android TV / Box funktioniert bzw. "bedienbar" wird ?

Grüße

**Comment by Fluffistar** [comment]
habe keine Box also kann ich das nicht testen

**Comment by magico1010** [comment]
ok. danke nochmal.

**Comment by bosangeros** [comment]
Bezüglich des atv Supports biete ich gerne an dir eine Box zukommen zu lassen.
Mittlerweile stauen sich die Boxen in meinem Wohnzimmerschrank…
Oder falls du das bezüglich der Adresse nicht möchtest empfehle ich mal folgenden Link : https://youtu.be/_dfOESBBTHM
Hab leider noch nie für android etwas geschrieben sonst hätte ich schon etwas in Absprache geforked :)

**Comment by bosangeros** [comment]
Gibt es hierzu in absehbarer Zeit ein Update?

**Comment by Fluffistar** [comment]
muss ich mal gucken  vlt für nen firetv stick ka wie kompatible es ist

**Comment by magico1010** [comment]
Danke für das Update.

Wollte informieren, dass es leider mit einem Android TV nicht funktioniert.
Habe es auf einem Sony Bravia und einer Mi Box S probiert.
Beim Start Crasht es manchmal und manchmal startet es aber dann "hängt" es und man kann
nichts bedienen.

**Comment by bosangeros** [comment]
@magico1010  kann ich so nicht bestätigen.
Sowohl auf meinem alten Sony 65X9305C als auch auf dem Shield TV Pro von 2019 läuft alles tadellos.

@Fluffistar meinst du es wäre möglich die auf den Seiten abbonierten Inhalte die ich in der watchlist habe auch abzugreifen ?
Dann könnte man z.b im Menü den Punkt Favoriten hinzufügen das wäre echt ne coole Geschichte.
